import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../prisma/prisma.service';
import { GoalsService } from '../goals/goals.service';
import { CreateInviteDto } from './invites.dto';
import { createToken, hashToken } from '../auth/token.util';
import { ActivityService } from '../activity/activity.service';

@Injectable()
export class InvitesService {
  constructor(private readonly prisma: PrismaService, private readonly config: ConfigService, private readonly goals: GoalsService, private readonly activity: ActivityService) {}
  async create(userId: string, dto: CreateInviteDto) {
    const token = createToken(); const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000); let goalId: string | undefined; let teamId: string | undefined;
    if (dto.targetType === 'goal') { const goal = await this.goals.assertCanManageMembers(userId, dto.targetId); if (goal.teamId) throw new BadRequestException('Team goals cannot be shared directly.'); goalId = goal.id; }
    else { const team = await this.prisma.team.findFirst({ where: { id: dto.targetId, OR: [{ ownerUserId: userId }, { members: { some: { userId, role: 'admin' } } }] } }); if (!team) throw new ForbiddenException('You cannot invite people to this team.'); teamId = team.id; }
    const invite = await this.prisma.inviteLink.create({ data: { tokenHash: hashToken(token), targetType: dto.targetType, goalId, teamId, role: 'viewer', createdByUserId: userId, expiresAt } });
    await this.activity.record(userId, 'invite_created', { goalId, teamId }, { targetType: dto.targetType });
    return { id: invite.id, targetType: invite.targetType, expiresAt, url: `${this.config.get('WEB_ORIGIN') ?? 'http://localhost:5173'}/invite/${token}` };
  }
  async preview(token: string) { const invite = await this.prisma.inviteLink.findFirst({ where: { tokenHash: hashToken(token), revokedAt: null, expiresAt: { gt: new Date() } }, include: { goal: { select: { id: true, name: true, teamId: true } }, team: { select: { id: true, name: true } } } }); if (!invite) throw new NotFoundException('Invite is invalid or expired.'); return { targetType: invite.targetType, name: invite.goal?.name ?? invite.team?.name, expiresAt: invite.expiresAt }; }
  async accept(userId: string, token: string) { const invite = await this.prisma.inviteLink.findFirst({ where: { tokenHash: hashToken(token), revokedAt: null, expiresAt: { gt: new Date() } }, include: { goal: true, team: true } }); if (!invite) throw new NotFoundException('Invite is invalid or expired.'); if (invite.targetType === 'goal' && (!invite.goal || invite.goal.teamId)) throw new BadRequestException('This goal cannot accept a direct invite.'); if (invite.targetType === 'team' && !invite.team) throw new NotFoundException('Team not found.'); const result = await this.prisma.$transaction(async (tx) => { const existingRedemption = await tx.inviteRedemption.findUnique({ where: { inviteLinkId_userId: { inviteLinkId: invite.id, userId } } }); if (existingRedemption) return { accepted: true, alreadyMember: true, targetType: invite.targetType, goalId: invite.goalId, teamId: invite.teamId }; if (invite.targetType === 'goal') { const goal = invite.goal!; if (goal.ownerUserId === userId) { await tx.inviteRedemption.create({ data: { inviteLinkId: invite.id, userId } }); return { accepted: true, alreadyMember: true, targetType: 'goal', goalId: goal.id }; } const count = await tx.goalMember.count({ where: { goalId: goal.id } }); if (count >= 3) throw new ConflictException('This goal already has the maximum of 3 guests.'); await tx.goalMember.upsert({ where: { goalId_userId: { goalId: goal.id, userId } }, update: {}, create: { goalId: goal.id, userId, role: invite.role } }); await tx.inviteRedemption.create({ data: { inviteLinkId: invite.id, userId } }); return { accepted: true, alreadyMember: false, targetType: 'goal', goalId: goal.id }; }
    const team = invite.team!; if (team.ownerUserId !== userId) await tx.teamMember.upsert({ where: { teamId_userId: { teamId: team.id, userId } }, update: {}, create: { teamId: team.id, userId, role: invite.role } }); await tx.inviteRedemption.create({ data: { inviteLinkId: invite.id, userId } }); return { accepted: true, targetType: 'team', teamId: team.id };
  }); await this.activity.record(userId, 'invite_accepted', { goalId: result.goalId ?? undefined, teamId: result.teamId ?? undefined }, { targetType: result.targetType }); return result; }
  async revoke(userId: string, inviteId: string) { const invite = await this.prisma.inviteLink.findFirst({ where: { id: inviteId, createdByUserId: userId } }); if (!invite) throw new UnauthorizedException('Invite not found.'); await this.prisma.inviteLink.update({ where: { id: inviteId }, data: { revokedAt: new Date() } }); await this.activity.record(userId, 'invite_revoked', { goalId: invite.goalId ?? undefined, teamId: invite.teamId ?? undefined }); return { revoked: true }; }
}
