import { ForbiddenException, Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateTeamDto, UpdateTeamDto, UpdateMemberRoleDto } from './teams.dto';
import { GoalsService } from '../goals/goals.service';

@Injectable()
export class TeamsService {
  constructor(private readonly prisma: PrismaService, private readonly goals: GoalsService) {}
  private async access(userId: string, teamId: string) { const team = await this.prisma.team.findFirst({ where: { id: teamId, OR: [{ ownerUserId: userId }, { members: { some: { userId } } }] }, include: { members: true } }); if (!team) throw new ForbiddenException('You do not have access to this team.'); const member = team.members.find((entry) => entry.userId === userId); return { team, role: team.ownerUserId === userId ? 'owner' : member?.role ?? 'viewer' }; }
  async list(userId: string) { return this.prisma.team.findMany({ where: { OR: [{ ownerUserId: userId }, { members: { some: { userId } } }] }, include: { members: { include: { user: { select: { id: true, name: true, email: true } } } }, goals: { where: { status: { not: 'cancelled' } }, select: { id: true, name: true, status: true } } }, orderBy: { updatedAt: 'desc' } }); }
  async get(userId: string, teamId: string) { await this.access(userId, teamId); return this.prisma.team.findFirst({ where: { id: teamId, OR: [{ ownerUserId: userId }, { members: { some: { userId } } }] }, include: { members: { include: { user: { select: { id: true, name: true, email: true } } } }, goals: { include: { steps: { include: { progresses: { where: { userId } } } } }, orderBy: { updatedAt: 'desc' } } } }); }
  async create(userId: string, dto: CreateTeamDto) { return this.prisma.team.create({ data: { ownerUserId: userId, name: dto.name.trim(), description: dto.description?.trim() || undefined } }); }
  async update(userId: string, teamId: string, dto: UpdateTeamDto) { const access = await this.access(userId, teamId); if (access.role !== 'owner' && access.role !== 'admin') throw new ForbiddenException('You cannot edit this team.'); return this.prisma.team.update({ where: { id: teamId }, data: { name: dto.name.trim(), description: dto.description?.trim() || null } }); }
  async remove(userId: string, teamId: string) { const access = await this.access(userId, teamId); if (access.role !== 'owner') throw new ForbiddenException('Only the team owner can remove it.'); await this.prisma.team.delete({ where: { id: teamId } }); return { deleted: true }; }
  async updateMember(userId: string, teamId: string, memberId: string, dto: UpdateMemberRoleDto) { const access = await this.access(userId, teamId); if (access.role !== 'owner' && access.role !== 'admin') throw new ForbiddenException('You cannot manage team members.'); if (!['admin', 'editor', 'viewer'].includes(dto.role)) throw new BadRequestException('Invalid role.'); const member = access.team.members.find((entry) => entry.id === memberId); if (!member) throw new NotFoundException('Member not found.'); if (member.userId === access.team.ownerUserId) throw new ForbiddenException('The team owner cannot be changed.'); if (access.role !== 'owner' && dto.role === 'admin') throw new ForbiddenException('Only the owner can assign admin.'); return this.prisma.teamMember.update({ where: { id: memberId }, data: { role: dto.role } }); }
  async removeMember(userId: string, teamId: string, memberId: string) { const access = await this.access(userId, teamId); if (access.role !== 'owner' && access.role !== 'admin') throw new ForbiddenException('You cannot manage team members.'); const member = access.team.members.find((entry) => entry.id === memberId); if (!member) throw new NotFoundException('Member not found.'); await this.prisma.teamMember.delete({ where: { id: memberId } }); const goals = await this.prisma.goal.findMany({ where: { teamId, status: 'active' }, select: { id: true } }); await Promise.all(goals.map((goal) => this.goals.recalculate(goal.id))); return { removed: true }; }
}
