import { NavLink, Route, Routes } from 'react-router-dom';

function DashboardPage() {
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">VISÃO GERAL</p><h1>Olá, vamos avançar?</h1><p className="muted">Acompanhe o que está em movimento hoje.</p></div><NavLink className="button button-primary" to="/goals/new">+ Nova meta</NavLink></div><div className="stat-grid"><StatCard label="Metas concluídas" value="0" tone="violet" /><StatCard label="Metas abertas" value="0" tone="blue" /><StatCard label="Este mês" value="0" tone="green" /><StatCard label="Este ano" value="0" tone="orange" /></div><div className="content-grid"><EmptyState title="Seu próximo passo começa aqui" body="Crie uma meta simples e transforme intenção em progresso visível." action="Criar primeira meta" href="/goals/new" /><div className="panel panel-highlight"><span className="panel-icon">✦</span><h2>Progresso que inspira</h2><p>O MissionLive organiza metas pessoais, compartilhadas e de equipes em um só lugar.</p></div></div></section>;
}
function GoalsPage() { return <section className="page"><div className="page-heading"><div><p className="eyebrow">SUAS METAS</p><h1>Metas</h1><p className="muted">Tudo que você quer colocar em movimento.</p></div><NavLink className="button button-primary" to="/goals/new">+ Nova meta</NavLink></div><EmptyState title="Nenhuma meta por enquanto" body="Comece com uma meta individual. Você poderá adicionar passos e convidar pessoas depois." action="Criar uma meta" href="/goals/new" /></section>; }
function TeamsPage() { return <section className="page"><div className="page-heading"><div><p className="eyebrow">COLABORAÇÃO</p><h1>Equipes</h1><p className="muted">Metas que avançam juntas.</p></div><button className="button button-secondary" type="button" disabled>+ Nova equipe</button></div><EmptyState title="Você ainda não participa de uma equipe" body="Quando alguém convidar você, suas equipes aparecerão aqui." action="Ver minhas metas" href="/goals" /></section>; }
function NewGoalPage() { return <section className="page narrow"><NavLink className="back-link" to="/goals">← Voltar para metas</NavLink><p className="eyebrow">NOVA META</p><h1>O que você quer realizar?</h1><p className="muted">A criação guiada estará disponível nesta área.</p><div className="panel form-placeholder"><label htmlFor="goal-name">Nome da meta</label><input id="goal-name" placeholder="Ex.: Correr 5 km" disabled /><button className="button button-primary" disabled type="button">Continuar</button></div></section>; }
function StatCard({ label, value, tone }: { label: string; value: string; tone: string }) { return <article className={`stat-card stat-${tone}`}><span className="stat-dot" aria-hidden="true" /><div><p>{label}</p><strong>{value}</strong></div></article>; }
function EmptyState({ title, body, action, href }: { title: string; body: string; action: string; href: string }) { return <div className="panel empty-state"><div className="empty-illustration" aria-hidden="true">◎</div><h2>{title}</h2><p>{body}</p><NavLink className="button button-primary" to={href}>{action}</NavLink></div>; }
export function MissionLiveWelcome() { return <><p className="eyebrow">MISSIONLIVE</p><h1>Suas metas, em movimento.</h1><p>Bootstrap inicial pronto.</p></>; }
export function App() { return <div className="app-shell"><header className="topbar"><NavLink className="brand" to="/"><span className="brand-mark">M</span><span>Mission<span className="brand-accent">Live</span></span></NavLink><nav className="desktop-nav" aria-label="Navegação principal"><NavItem to="/" label="Início" icon="⌂" /><NavItem to="/goals" label="Metas" icon="✓" /><NavItem to="/teams" label="Equipes" icon="◉" /></nav><button className="avatar-button" type="button" aria-label="Abrir perfil">ML</button></header><main><Routes><Route path="/" element={<DashboardPage />} /><Route path="/goals" element={<GoalsPage />} /><Route path="/goals/new" element={<NewGoalPage />} /><Route path="/teams" element={<TeamsPage />} /><Route path="*" element={<DashboardPage />} /></Routes></main><nav className="mobile-nav" aria-label="Navegação móvel"><NavItem to="/" label="Início" icon="⌂" /><NavItem to="/goals" label="Metas" icon="✓" /><NavItem to="/teams" label="Equipes" icon="◉" /></nav></div>; }
function NavItem({ to, label, icon }: { to: string; label: string; icon: string }) { return <NavLink className={({ isActive }) => `nav-item${isActive ? ' active' : ''}`} to={to} end={to === '/'}><span aria-hidden="true">{icon}</span><span>{label}</span></NavLink>; }
