PRAGMA foreign_keys=OFF;

CREATE TABLE "User" ("id" TEXT NOT NULL PRIMARY KEY, "email" TEXT NOT NULL, "name" TEXT NOT NULL, "avatarUrl" TEXT, "passwordHash" TEXT, "emailVerifiedAt" DATETIME, "status" TEXT NOT NULL DEFAULT 'active', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "Account" ("id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerAccountId" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Session" ("id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "refreshTokenHash" TEXT NOT NULL, "expiresAt" DATETIME NOT NULL, "revokedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "AuthToken" ("id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" DATETIME NOT NULL, "consumedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuthToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Category" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "Goal" ("id" TEXT NOT NULL PRIMARY KEY, "ownerUserId" TEXT NOT NULL, "teamId" TEXT, "name" TEXT NOT NULL, "description" TEXT, "categoryId" TEXT, "customCategory" TEXT, "tagsJson" TEXT NOT NULL DEFAULT '[]', "startDate" DATETIME NOT NULL, "endDate" DATETIME, "status" TEXT NOT NULL DEFAULT 'active', "completedAt" DATETIME, "completionMode" TEXT, "completedByUserId" TEXT, "completionOverrideReason" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Goal_ownerUserId_fkey" FOREIGN KEY ("ownerUserId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Goal_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "Goal_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "Goal_completedByUserId_fkey" FOREIGN KEY ("completedByUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "GoalMember" ("id" TEXT NOT NULL PRIMARY KEY, "goalId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" TEXT NOT NULL, "joinedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "GoalMember_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "Goal" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "GoalMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "GoalStep" ("id" TEXT NOT NULL PRIMARY KEY, "goalId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "position" INTEGER NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "GoalStep_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "Goal" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "GoalStepProgress" ("id" TEXT NOT NULL PRIMARY KEY, "goalStepId" TEXT NOT NULL, "userId" TEXT NOT NULL, "completed" BOOLEAN NOT NULL DEFAULT false, "completedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "GoalStepProgress_goalStepId_fkey" FOREIGN KEY ("goalStepId") REFERENCES "GoalStep" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "GoalStepProgress_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Team" ("id" TEXT NOT NULL PRIMARY KEY, "ownerUserId" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "avatarUrl" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Team_ownerUserId_fkey" FOREIGN KEY ("ownerUserId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "TeamMember" ("id" TEXT NOT NULL PRIMARY KEY, "teamId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" TEXT NOT NULL, "joinedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "TeamMember_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "TeamMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "InviteLink" ("id" TEXT NOT NULL PRIMARY KEY, "tokenHash" TEXT NOT NULL, "targetType" TEXT NOT NULL, "teamId" TEXT, "goalId" TEXT, "role" TEXT NOT NULL, "createdByUserId" TEXT NOT NULL, "expiresAt" DATETIME NOT NULL, "revokedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "InviteLink_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "InviteLink_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "Goal" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "InviteLink_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "InviteRedemption" ("id" TEXT NOT NULL PRIMARY KEY, "inviteLinkId" TEXT NOT NULL, "userId" TEXT NOT NULL, "acceptedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InviteRedemption_inviteLinkId_fkey" FOREIGN KEY ("inviteLinkId") REFERENCES "InviteLink" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "InviteRedemption_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Plan" ("id" TEXT NOT NULL PRIMARY KEY, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "limitsJson" TEXT NOT NULL DEFAULT '{}', "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "Subscription" ("id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "planId" TEXT NOT NULL, "status" TEXT NOT NULL, "currentPeriodStart" DATETIME, "currentPeriodEnd" DATETIME, "provider" TEXT, "providerSubscriptionId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Subscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Subscription_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "Account_userId_idx" ON "Account"("userId");
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");
CREATE INDEX "AuthToken_userId_idx" ON "AuthToken"("userId");
CREATE INDEX "AuthToken_expiresAt_idx" ON "AuthToken"("expiresAt");
CREATE UNIQUE INDEX "AuthToken_type_tokenHash_key" ON "AuthToken"("type", "tokenHash");
CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name");
CREATE INDEX "Goal_ownerUserId_idx" ON "Goal"("ownerUserId");
CREATE INDEX "Goal_teamId_idx" ON "Goal"("teamId");
CREATE INDEX "Goal_categoryId_idx" ON "Goal"("categoryId");
CREATE INDEX "Goal_status_idx" ON "Goal"("status");
CREATE INDEX "GoalMember_userId_idx" ON "GoalMember"("userId");
CREATE UNIQUE INDEX "GoalMember_goalId_userId_key" ON "GoalMember"("goalId", "userId");
CREATE INDEX "GoalStep_goalId_idx" ON "GoalStep"("goalId");
CREATE UNIQUE INDEX "GoalStep_goalId_position_key" ON "GoalStep"("goalId", "position");
CREATE INDEX "GoalStepProgress_userId_idx" ON "GoalStepProgress"("userId");
CREATE UNIQUE INDEX "GoalStepProgress_goalStepId_userId_key" ON "GoalStepProgress"("goalStepId", "userId");
CREATE INDEX "Team_ownerUserId_idx" ON "Team"("ownerUserId");
CREATE INDEX "TeamMember_userId_idx" ON "TeamMember"("userId");
CREATE UNIQUE INDEX "TeamMember_teamId_userId_key" ON "TeamMember"("teamId", "userId");
CREATE UNIQUE INDEX "InviteLink_tokenHash_key" ON "InviteLink"("tokenHash");
CREATE INDEX "InviteLink_teamId_idx" ON "InviteLink"("teamId");
CREATE INDEX "InviteLink_goalId_idx" ON "InviteLink"("goalId");
CREATE INDEX "InviteLink_expiresAt_idx" ON "InviteLink"("expiresAt");
CREATE INDEX "InviteRedemption_userId_idx" ON "InviteRedemption"("userId");
CREATE UNIQUE INDEX "InviteRedemption_inviteLinkId_userId_key" ON "InviteRedemption"("inviteLinkId", "userId");
CREATE UNIQUE INDEX "Plan_code_key" ON "Plan"("code");
CREATE INDEX "Subscription_userId_idx" ON "Subscription"("userId");
CREATE INDEX "Subscription_planId_idx" ON "Subscription"("planId");

PRAGMA foreign_keys=ON;
